name: Terraform Demo Plan

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "azure_credentials=${{ secrets.AZURE_CREDENTIALS }}" -out=tfplan

      - name: Terraform Apply (demo-safe)
        run: terraform apply -var "azure_credentials=${{ secrets.AZURE_CREDENTIALS }}" -auto-approve tfplan
